FROM registry.access.redhat.com/ubi8/ubi:latest
RUN yum update -y && \
    yum install -y logrotate && \
    yum clean all

# Create a logrotate config file
RUN echo "/opt/apache/tomcat/base/logs/*.* {daily size 300M missingok rotate 5 compress delaycompress notifempty create}"> /etc/logrotate.d/logrotate.conf


RUN touch /etc/logrotate.status
RUN chmod 666 /etc/logrotate.status

# Update CMD to use the custom status file
CMD while true; do logrotate -s /etc/logrotate.status /etc/logrotate.d/logrotate.conf; sleep 86400; done
